# pnpm 会将这些目录中的包视为同一工作区的一部分，可以共享依赖
packages:
  - web/*
  - shared
catalog:
  # ~ 会匹配最近的小版本依赖包，比如~1.2.3会匹配所有1.2.x的包，但是不包括1.3.0
  # ^ 会匹配最新的大版本依赖包，比如^1.2.3会匹配所有1.x.x的包，包括1.3.0，但是不包括2.0.0
  typescript: ~5.8.3
  rimraf: ~6.0.1
  eslint: ~9.27.0
  axios: ~1.8.1
  vue: ~3.5.13
  react: ~18.2.0
  react-dom: ~18.2.0