# pnpm 会将这些目录中的包视为同一工作区的一部分，可以共享依赖
packages:
  - packages/*
  - shared
  - services/*
  - '!** /node_modules'  # 排除所有目录下的 node_modules 文件夹
catalog:
  # ~ 会匹配最近的小版本依赖包，比如~1.2.3会匹配所有1.2.x的包，但是不包括1.3.0
  # ^ 会匹配最新的大版本依赖包，比如^1.2.3会匹配所有1.x.x的包，包括1.3.0，但是不包括2.0.0
  # eslint prettier 代码规范（ESLint 9.x 对应其他依赖兼容版本）
  'eslint': ~9.27.0
  'prettier': ~3.5.1
  '@eslint/js': ~9.27.0  # ESLint 9.x 核心规则包
  'typescript-eslint': ~8.40.0  # TS 集成核心包（兼容 ESLint 9.x）
  '@typescript-eslint/eslint-plugin': ~8.40.0  # TS 规则插件
  '@typescript-eslint/parser': ~8.40.0  # TS 解析器
  'eslint-plugin-prettier': ~5.2.1  # Prettier 与 ESLint 桥接（兼容 ESLint 9.x）
  'eslint-config-prettier': ~9.1.0  # 关闭与 Prettier 冲突的 ESLint 规则
  'eslint-plugin-vue': ~9.29.0  # Vue 规则插件（兼容 ESLint 9.x 和 Vue 3.5+）
  'vue-eslint-parser': ~9.4.3  # Vue 模板解析器（配合 ESLint 9.x 使用）
  'eslint-plugin-react': ~7.37.1  # React 规则插件（兼容 ESLint 9.x 和 React 18+）
  'eslint-plugin-react-hooks': ~5.0.0  # React Hooks 规则（兼容 ESLint 9.x）
  'eslint-plugin-react-refresh': ~0.4.14  # React 热更新支持

  'typescript': ~5.8.3
  'rimraf': ~6.0.1
  'axios': ~1.8.1
  'vue': ~3.5.13
  'react': ~18.2.0
  'react-dom': ~18.2.0

peerDependencyRules:
  allowedVersions:
    'typescript-eslint>eslint': ^9.0.0
    '@typescript-eslint/eslint-plugin>eslint': ^9.0.0
    '@typescript-eslint/parser>eslint': ^9.0.0
    '@typescript-eslint/type-utils>eslint': ^9.0.0
    '@typescript-eslint/utils>eslint': ^9.0.0
    # 补充 Prettier 和框架插件的 peerDependency 兼容规则
    'eslint-plugin-prettier>eslint': ~9.27.0
    'eslint-plugin-prettier>prettier': ~3.5.1
    'eslint-config-prettier>eslint': ~9.27.0
    'eslint-plugin-vue>eslint': ~9.27.0
    'eslint-plugin-vue>vue-eslint-parser': ~9.4.3
    'eslint-plugin-react>eslint': ~9.27.0
